services:
  mlops-iris-api:
    build:
      context: .
      dockerfile: src/api/Dockerfile 
    deploy:
      replicas: 3
    expose:
      - "8000"

  nginx:
    build:
      context: deployments/nginx/
      dockerfile: Dockerfile
    container_name: nginx_revproxy
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./deployments/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mlops-iris-api
      
